//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmSpy.CommandLine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AsmSpy_CommandLine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsmSpy_CommandLine() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsmSpy.CommandLine.AsmSpy.CommandLine", typeof(AsmSpy_CommandLine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (AlternativeVersionFound).
        /// </summary>
        internal static string AlternativeVersionFound {
            get {
                return ResourceManager.GetString("AlternativeVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  by .
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ConsoleVisualizer_Visualize__0_ {
            get {
                return ResourceManager.GetString("ConsoleVisualizer_Visualize__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0}.
        /// </summary>
        internal static string ConsoleVisualizer_VisualizeAssemblyReferenceInfo______0_ {
            get {
                return ResourceManager.GetString("ConsoleVisualizer_VisualizeAssemblyReferenceInfo______0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0}.
        /// </summary>
        internal static string ConsoleVisualizer_VisualizeAssemblyReferenceInfo____0_ {
            get {
                return ResourceManager.GetString("ConsoleVisualizer_VisualizeAssemblyReferenceInfo____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ConsoleVisualizer_VisualizeAssemblyReferenceInfo__0_ {
            get {
                return ResourceManager.GetString("ConsoleVisualizer_VisualizeAssemblyReferenceInfo__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailing only conflicting assembly references..
        /// </summary>
        internal static string Detailing_only_conflicting_assembly_references {
            get {
                return ResourceManager.GetString("Detailing_only_conflicting_assembly_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AssemblySource.
        /// </summary>
        internal static string Invalid_AssemblySource {
            get {
                return ResourceManager.GetString("Invalid_AssemblySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Location: {0}.
        /// </summary>
        internal static string Location_ {
            get {
                return ResourceManager.GetString("Location_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assemblies files found in directory.
        /// </summary>
        internal static string No_assemblies_files_found_in_directory {
            get {
                return ResourceManager.GetString("No_assemblies_files_found_in_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference: .
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: {0}.
        /// </summary>
        internal static string Source_ {
            get {
                return ResourceManager.GetString("Source_", resourceCulture);
            }
        }
    }
}
